## **Numpy**

    NumPy is the fundamental package for scientific computing in Python. It is a Pythonlibrary that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
[https://numpy.org/doc/stable/user/whatisnumpy.html]

In [68]:
import numpy as np
import matplotlib.pyplot as plt # for plot graph

In [67]:
# If I forgot what is function do , I can type [function?]
# such as
# np.array?

**numpy.array**
- numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
- Create an array from data type (i.e list , tuple and etc) to numpy array

In [75]:
# conversion from list to NumPy arrays
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [74]:
# conversion from tuples to NumPy arrays
a = np.array((6, 7, 8, 9, 10))
print(a)
print(type(a))
print(a.dtype)

[ 6  7  8  9 10]
<class 'numpy.ndarray'>
int64


In [76]:
# If I add many data type in np.array, It convert to object
a = np.array((6, [7], 8, 9, 10))
print(a)
print(type(a))
print(a.dtype)
# This means that a is a numpy array where each element is stored as an object.
# This is not typical for numerical arrays, as it loses some of the performance
# and memory efficiency benefits of using numpy arrays with homogeneous data types. 

[6 list([7]) 8 9 10]
<class 'numpy.ndarray'>
object


/tmp/ipykernel_1378134/1770930003.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array((6, [7], 8, 9, 10))


In [20]:
# Information for dtype(data type) [https://numpy.org/doc/stable/user/basics.types.html]
a = np.array([1, 2, 3, 5, 7], dtype='i')
print(a)
print(type(a))
print(a.dtype)

print('____________________')

b = np.array([1, 2, 3, 5, 7], dtype='f')
print(b)
print(type(b))
print(b.dtype)

[1 2 3 5 7]
<class 'numpy.ndarray'>
int32
____________________
[1. 2. 3. 5. 7.]
<class 'numpy.ndarray'>
float32


In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
2
(2, 3)


In [28]:
# It should be equal all dimension
a = np.array([[1, 2, 3, 4], [4, 5, 6]])

/tmp/ipykernel_1378134/1201062784.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1, 2, 3, 4], [4, 5, 6]])


In [29]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a.ndim)
print(a.shape)

3
(2, 2, 2)


**c is a 3D array:**
- The first dimension (or axis) has 2 elements: [[1, 2], [3, 4]] and [[5, 6], [7, 8]].
- The second dimension (or axis) also has 2 elements: [1, 2] and [3, 4] within each sub-array.
- The third dimension (or axis) has 2 elements: 1 and 2 within each sub-sub-array.

**How to access value**
- Bracket Indexing ([][] notation):
- Comma-Separated Indices ([,] notation):


In [34]:
a = np.array([[1, 2, 3, 4, 5] ,[6, 7, 8, 9, 10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
# Bracket Indexing ([][] notation):
a[0][1] # [0] first row [1] second column

2

In [38]:
# Comma-Separated Indices ([,] notation):
a[0, 1] # [0] first row [1] second column

2

In [39]:
a = np.array([[[1], [2], [3]], [[4], [5], [6]]])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [40]:
print("Array a:") # like rgb
print(a)
print("Shape of a:", a.shape)
print("Dimension :", a.ndim)
print("Type : ", a.dtype)
print("")

# Array b
print("Array b:")
print(b)
print("Shape of b:", b.shape)
print("Dimension :", b.ndim)
print("Type : ", b.dtype)

Array a:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
Shape of a: (2, 3, 1)
Dimension : 3
Type :  int64

Array b:
[[1 2 3]
 [4 5 6]]
Shape of b: (2, 3)
Dimension : 2
Type :  int64


In [47]:
# ??
a = np.array(3)
print(a)
print(type(a))
print(a.dtype)


3
<class 'numpy.ndarray'>
int64


**np.arange**

- numpy.arange([start, ]stop, [step, ]dtype=None, *, device=None, like=None)


** np.arange **


In [48]:
a = np.arange(5)

In [49]:
# a: Displays the array a in a format suitable for direct inspection 
# in an interactive session. In Jupyter notebooks, it typically formats 
# the array in a neat, readable manner.
a

array([0, 1, 2, 3, 4])

In [50]:
# print(a): Prints the array a explicitly using the print() function,
# which may result in a slightly different formatting, especially when
# printing multiple arrays or when mixed with other output.
print(a)

[0 1 2 3 4]


In [51]:
b = np.arange(20, 30)
print(b)

[20 21 22 23 24 25 26 27 28 29]


In [52]:
c = np.arange(20, 30, 2)
print(c)

[20 22 24 26 28]


In [53]:
# When you use print(range(10)), it displays range(0, 10)
# because range is a special type of sequence object
# that represents a range of numbers. To see the actual numbers,
# you need to convert the range object to a list or iterate through it.
# This approach provides memory efficiency and performance benefits,
# especially for large ranges.
print(range(10))

range(0, 10)


In [54]:
type(range(10))

range

**np.random.permutation**
- np.random.permutation(x)
- Randomly permute a sequence, or return a permuted range.
    If x is an integer, randomly permute np.arange(x).
    If x is an array, make a copy and shuffle the elements randomly.

In [77]:
# np.random.permutation?

In [55]:
A = np.random.permutation(5)
print(A)

[3 1 4 0 2]


In [56]:
B = np.random.permutation(np.arange(5))
print(B)

[4 0 3 2 1]


In [78]:
# np.random.randint?

- np.random.randint